### PR TITLE
Ivan's ZK-ML research and sad thoughts

### PR DESCRIPTION
**Pull request by IvanAnishchuk**
My thoughts on sumcheck/lookup based ZK-ML prover in somewhat consumable form. There are no conclusions, no clear results, only promises. I don't like this but I most likely won't continue this further. This is very different from a frontend app showing some simple use of some available technology (your typical hackathon or grant-supported project), this topic needs core research and completely new tech and definitive answers (even not talking about practical results) will require more time than I have a survival budget for. An aligned job or internship would make more sense but my credentials for getting one are somewhat lacking (am open to offers, not expecting any).

I decided a good log is better than a video of CLI doing things. I'm not a frontend app builder.

### CODE REVIEW

**Comment by leolara** [comment]
Please follow the instructions, you have to create a subdirectory and put there a README

**Comment by rutefig** [comment]
@IvanAnishchuk please check the comment

**Comment by IvanAnishchuk** [comment]
@leolara @rutefig Fixed and rebased.

**Comment by rutefig** [comment]
> @leolara @rutefig Fixed and rebased.

thank you 🙏🏼

**Pull request merged**
