### PR TITLE
Submit Modity project by Box

### PR DESCRIPTION
**Pull request by nishuzumi**
Modity is a browser-based Jupyter Notebook-like environment for Solidity, providing an interactive development experience specifically for writing and testing smart contracts. Additionally, Modity offers the capability to interact with EVM-compatible public blockchains, allowing developers to write, test, and deploy smart contracts directly in their web browser.

### CODE REVIEW

**Comment by rutefig** [comment]
@nishuzumi pls can you remove the change on the `README_template.md` file, also you can add only the `README.md` file on your project folder and remove all the code, just provide a link for your github repo

**Comment by nishuzumi** [comment]
@rutefig Done

**Comment by rutefig** [comment]
@nishuzumi can you also discard the changes on the `README_template.md` pls?

**Comment by nishuzumi** [comment]
@rutefig I'm sorry! Solved this time

**Pull request merged**
