### PR TITLE
ZKCX - Zero Knowledge Certificate Exchange in Remote SIM Provisioning Protocol , an eSIM Technology

### PR DESCRIPTION
**Pull request by ArpitxGit**

### CODE REVIEW

**Comment by rutefig** [comment]
@ArpitxGit you can remove all the codebase from here and only have the `README.md` file, great job 🎉

**Comment by rutefig** [comment]
@ArpitxGit check the comment pls 😅

**Comment by ArpitxGit** [comment]
Hey @rutefig , thankyou so much, just saw the last comment, doing it right now😇

**Comment by ArpitxGit** [comment]
- Only Readme with updated URLs.
Thanks again @rutefig  :)

**Pull request merged**
