### PR TITLE
AI Training Data Selling with Privacy Protection (for client)   

### PR DESCRIPTION
**Pull request by BaoNinh2808**
AI Training Data Selling with Privacy Protection (for client)

Team members:
- Ninh Quoc Bao
- Nguyen Minh Nhat
- Phan Van Nhat
- Truong Vinh Kien

### CODE REVIEW

**Comment by rutefig** [comment]
@BaoNinh2808 remove the changes for the `README_template.md` file

**Comment by rutefig** [comment]
@BaoNinh2808 pls follow the instructions for the submission and check the comments

**Comment by BaoNinh2808** [comment]
> @BaoNinh2808 pls follow the instructions for the submission and check the comments

I have removed changes in README-template.md, please check for me. Tks

**Comment by leolara** [comment]
@BaoNinh2808 if you look at the diff there is still a change

**Comment by BaoNinh2808** [comment]
> @BaoNinh2808 if you look at the diff there is still a change

I copy and paste the README-templates.md file to my repo, so I don't know where is the change in this file. And I see the announce "This branch has no conflicts with the base branch"

**Pull request merged**
